### PR TITLE
New setup for BILLY and VCR

### PR DESCRIPTION
**Pull request by ZmagoD**
#2 
@decareano, @tansaku, @Proskurina, @jpb
1. In these PR I had setup the billy gem to catch the google maps api calls 
2. I change the configuration of the VCR gem for using with cucumber ( like in the LocalSupport app)
I have one problem left on # features/welcome.feature:15 spec. If I add the @billy tag which uses the :poltergeist_billy driver it throw me an error that there is no selector area[title="\"Driver volunteer\""]. The other test passes either way.

### CODE REVIEW

**Comment by tansaku** [comment]
great work @ZmagoD - will have a closer look at this tomorrow  ...

**Comment by decareano** [comment]
Thanks @zmagod. Could you run the "billy_sample.feature" without the @vcr tag? Just @billy and @javascript. Please tell me if: 1. you can stub the request and 2. If it does stub the request, can you run the test in ISOLATION? I am reading that billy and vcr/webmock do not work great together.

**Comment by tansaku** [comment]
@ZmagoD I replicated your error

```
expected to find css "area[title=\"\\\"Driver volunteer\\\"\"]" 1 time but there were no matches. Also found "", which matched the selector but not all filters. (RSpec::Expectations::ExpectationNotMetError)
      ./features/step_definitions/welcome_steps.rb:18:in `/^I should see a pin on the map with Driver volunteer opportunity$/'
      features/welcome.feature:17:in `Then I should see a pin on the map with Driver volunteer opportunity'
```

**Comment by tansaku** [comment]
@decareano I just tried what you suggested and I got this (although I was going underground at the time):

```
[tansaku@Samuels-MacBook-Pro-2:~/Documents/Github/Proskurina/doit_rails ((9d86f8a...))]$ 
→ cucumber features/billy_sample.feature 
Running via Spring preloader in process 31421
[DEPRECATION] `restore_cache` is deprecated as cache files are dynamically checked. Use `reset_cache` if you just want to clear the cache.
Using the default profile...
Feature: Stubbing via billy

  @javascript @billy
  Scenario: Test billy       # features/billy_sample.feature:4
DARLA notice: 450
    And a stub for a website # features/step_definitions/billy_sample_steps.rb:5
      Timed out waiting for response to {"id":"b71429ca-f3a5-43ba-a743-43509f0106da","name":"visit","args":["http://www.yahoo.com/"]}. It's possible that this happened because something took a very long time (for example a page load was slow). If so, setting the Poltergeist :timeout option to a higher value will help (see the docs for details). If increasing the timeout does not help, this is probably a bug in Poltergeist - please report it to the issue tracker. (Capybara::Poltergeist::TimeoutError)
      ./features/step_definitions/billy_sample_steps.rb:7:in `/^a stub for a website$/'
      features/billy_sample.feature:5:in `And a stub for a website'

Failing Scenarios:
cucumber features/billy_sample.feature:4 # Scenario: Test billy

1 scenario (1 failed)
1 step (1 failed)
0m31.784s
```

Remember you can easily run Zmago's code yourself by just pulling a copy of his code from https://github.com/ZmagoD/doit_rails  That's what I did to execute his code.  Now I'm underground without internet so don't think I can respond to your points 1 and 2, but will keep looking through the code ...

**Comment by Proskurina** [comment]
@ZmagoD Thank you! Billy is a new thing to me, so thank you for setting it up.
The test failing might mean that billy does not communicate with vcr yet.
After today morning discussion with @tansaku I did some research and I can see here https://github.com/oesmith/puffing-billy/issues/54 that using billy with vcr is problematic and billy's collaborator is against it. Though this discussion in vcr issues is very interesting https://github.com/vcr/vcr/issues/187 , will try to investigate it further. 

@ZmagoD @decareano @C9905557 if you want me to add you as collaborators, please let me know, (after today discussion with @tansaku it seems the easiest way to proceed).

**Comment by decareano** [comment]
@jana, please do. The more eyes we have on this issue the better. 
@tansaku, I did get @zmagod branch on my repo. But he used the `@vcr` tag in the feature and wanted to see what results he got on his system with the tag removed. Can I look at the branch where you got the results posted above? curious about your `test.log` file.

**Comment by ZmagoD** [comment]
@decareano runnig "billy_sample.feature" without "@vcr" tag these error : 
    `And a stub for a website # features/step_definitions/billy_sample_steps.rb:5
      Timed out waiting for response to {"id":"e4ef7c12-1b5b-41c5-961a-cf507beb2f7a","name":"visit","args":["http://www.yahoo.com/"]}. It's possible that this happened because something took a very long time (for example a page load was slow). If so, setting the Poltergeist :timeout option to a higher value will help (see the docs for details). If increasing the timeout does not help, this is probably a bug in Poltergeist - please report it to the issue tracker. (Capybara::Poltergeist::TimeoutError)
      ./features/step_definitions/billy_sample_steps.rb:7:in `/^a stub for a website$/'
      features/billy_sample.feature:5:in `And a stub for a website'`

**Comment by ZmagoD** [comment]
@decareano in these commit I changed the Capybara.current_driver from ":poltergeist" to ":selenium_billy" and all the test passes.

**Comment by Proskurina** [comment]
@ZmagoD Wow! That's awesome!
At first it froze couple of times, but now it works just fine.

**Comment by ZmagoD** [comment]
I'm running on Ubuntu 15.10 and works smoothly. Try to delete the "billy" cache the "req_catche" folder and then run cucumber again online.

**Comment by Proskurina** [comment]
@ZmagoD I am on Mac, El Capitan. 

Tests behave weirdly when online. The right windows are being opened in Firefox, but they freeze for 1 min or so, then this error appears `Net::ReadTimeout (Net::ReadTimeout)`. In the end it says 2 test failed but all steps passed. And now it gives  ```WARNING: There appears to be a bug in WebMock's after_request hook and VCR is attempting to work around it. Some VCR features may not work properly.```
Now 3 tests failed, but all steps passed.
One round of tests takes 4 to 6 mins.

When offline all is fine.

**Comment by ZmagoD** [comment]
Hmm strange. Here is my run.
screenshot from 2016-01-04 23 49 26

**Comment by ZmagoD** [comment]
Maybe if we fix that "restore_cache" deprecation will do the trick. I will try it tomorrow.

**Comment by tansaku** [comment]
@ZmagoD good progress - I just pulled out your latest, but having trouble switching due to the contents of the 'features/req_cache' - might want to check in that dir or add to .gitignore as appropriate.  Check it in with .keep perhaps?

**Comment by tansaku** [comment]
and running this locally for me seems to get stuck:

https://www.dropbox.com/s/c5lruugihyc5o5o/Screenshot%202016-01-05%2008.58.08.png?dl=1

but perhaps because I have some cruft left over ...

**Comment by Proskurina** [comment]
@ZmagoD it works for me now!

**Comment by ZmagoD** [comment]
@Proskurina  Ok let's wait for @decareano  and @tansaku  to check this out and than we have to figure out how to implement this into LocalSupport.

**Comment by tansaku** [comment]
@ZmagoD it works for me too - online and offline - fantastic work!  I'll be really interested to look in detail and the set up.  Perhaps you could write a blog post or similar on your understanding of how it all works?

**Comment by ZmagoD** [comment]
@tansaku Ok. But for integrate this in LocalSupport we will have to configure vcr to not pick up the FakeGoogleGeocode sinatra app or only use puffing-billy on the browser proxy or try to get rid of this sinatra app and let the vcr to pick that instead

**Comment by tansaku** [comment]
@ZmagoD sure.  Personally I'm not sure why the sinatra app is necessary.  Perhaps we can get @mtc2013 and @johnnymo87 in on the discussion.  My sense is that they put that in.

**Comment by tansaku** [comment]
@ZmagoD @decareano any more thoughts on this - are you thinking about a pull request on LocalSupport?  @ZmagoD would still love to see a blog from you on how you got this all working

**Comment by ZmagoD** [comment]
@tansaku, @decareano and I had discussed on tuesday about billy gem and the Billy only #4 pull request. We want to setup only the billy gem to catch the browser requests but for now unsuccessfully. If we manage to do it right we can avoid troubles like it was in the https://github.com/AgileVentures/LocalSupport/pull/198 pull request where VCR was picking requests of the FakeGoogleGeocode Sinatra app

**Comment by tansaku** [comment]
@ZmagoD good to know - can you let us know which branch you're working on?  Maybe even just leave an open WIP pull request?

I'm switching to 100% Agile Ventures and I want to move more resources onto this problem.  The client is prioritizing the do-it integration and having the whole testing strategy sorted is a pre-requisite for taking the whole thing into production I think.

Many thanks in advance

**Comment by johnnymo87** [comment]
@ZmagoD Sam, Michael, and I were chatting yesterday, and I suggested that if the `FakeGoogleGeocode` sinatra app is in your way, you should just nuke it. 

That said, I don't fully understand how puffing billy works. Is it normal for it generate 10000 lines? Are these lines going to remain forever the same, or are the going to constantly churn? If they're churning, is it only due to google tweaking it API, or is it churning every time a timestamp on a request differs?

**Comment by ZmagoD** [comment]
Hi @johnnymo87 I was thinking that if is possible to leave your sinatra app there and make work only with billy gem( it's supposed that leaves the calls for FakeGoogleGeocode out ).

**Comment by tansaku** [comment]
that's good to know @ZmagoD however I don't think the sinatra app is doing anything that VCR can't do - and I'm slightly more comfortable with VCR than a custom solution, but I'm open to ideas

**Pull request merged**
